const gunDataObj = {
  gunNameObj: {iw8_ar_akilo47: 'AK-47',
  iw8_ar_anovember94: 'an-94',
  iw8_ar_asierra12: 'Oden',
  iw8_ar_falima: 'FAL',
  iw8_ar_falpha: 'FR 5.56',
  iw8_ar_galima: 'CR-56 AMAX',
  iw8_ar_kilo433: 'Kilo-141',
  iw8_ar_mcharlie: 'M13',
  iw8_ar_mike4: 'M4A1',
  iw8_ar_scharlie: 'FN Scar 17',
  iw8_ar_sierra552: 'Grau 5.56',
  iw8_ar_tango21: 'RAM-7',
  iw8_ar_valpha: 'V-Alpha',
  iw8_knife: 'Combat Knife',
  iw8_la_gromeo: 'PILA',
  iw8_la_juliet: 'JOKR',
  iw8_la_kgolf: 'Strela-P',
  iw8_la_rpapa7: 'RPG-7',
  iw8_la_mike32: 'Milkor MGL',
  iw8_lm_dblmg: 'MP Juggernaut',
  iw8_lm_kilo121: 'M91',
  iw8_lm_lima86: 'SA87',
  iw8_lm_mgolf34: 'MG34',
  iw8_lm_mgolf36: 'Holger-26',
  iw8_lm_mkilo3: 'Bruen MK9',
  iw8_lm_pkilo: 'PKM',
  iw8_lm_sierrax: 'Sierrax LMG',
  iw8_me_akimboblunt: 'Kali Sticks',
  iw8_me_kalistick: 'Kali Sticks',
  iw8_me_riotshield: 'Riot Shield',
  iw8_pi_cpapa: '0.357',
  iw8_pi_decho: '.50 GS',
  iw8_pi_golf21: 'X16',
  iw8_pi_mike1911: '1911',
  iw8_pi_mike9: 'Renetti',
  iw8_pi_mike9a3: 'Renetti',
  iw8_pi_papa320: 'M19',
  iw8_sh_aalpha12: 'JAK-12',
  iw8_sh_charlie725: '725',
  iw8_sh_dpapa12: 'R9-0',
  iw8_sh_mike26: 'VLK Rogue',
  iw8_sh_oscar12: 'Origin 12',
  iw8_sh_romeo870: 'Model 680',
  iw8_sm_augolf: 'AUG',
  iw8_sm_beta: 'PP19 Bizon',
  iw8_sm_mpapa5: 'MP5',
  iw8_sm_mpapa7: 'MP7',
  iw8_sm_papa90: 'P90',
  iw8_sm_smgolf45: 'Striker 45',
  iw8_sm_uzulu: 'Uzi',
  iw8_sm_victor: 'Fennec Mk9',
  iw8_sn_alpha50: 'AX-50',
  iw8_sn_crossbow: 'Crossbow',
  iw8_sn_delta: 'Dragunov',
  iw8_sn_hdromeo: 'HDR',
  iw8_sn_kilo98: 'Kar98k',
  iw8_sn_mike14: 'EBR-14',
  iw8_sn_sbeta: 'Mk2 Carbine',
  iw8_sn_sksierra: 'SKS',
  iw8_sn_xmike109: 'Rytec AMR',
  iw8_sn_romeo700: 'Remington 700',
  equip_gas_grenade: 'Gas Grenade',
  equip_snapshot_grenade: 'Snapshot Grenade',
  equip_decoy: 'Decoy',
  equip_smoke: 'Smoke Grenade',
  equip_concussion: 'Concussion Grenade',
  equip_hb_sensor: 'HB Sensor',
  equip_flash: 'Flash Grenade',
  equip_adrenaline: 'Adrenaline Shot',
  equip_frag: 'Fragmentation Grenade',
  equip_thermite: 'Thermite Grenade',
  equip_semtex: 'Semtex',
  equip_claymore: 'Claymore Mine',
  equip_c4: 'C4 Explosive',
  equip_at_mine: 'Anti Tank Mine',
  equip_throwing_knife: 'Throwing Knife',
  equip_molotov: 'Molotov Cocktail',
  },
  gunStatTitle: {
    hits: 'Hits',
    kills: 'Kills',
    kdRatio: 'KD Ratio',
    headshots: 'Head Shots',
    accuracy: 'Accuracy',
    shots: 'Shots',
    deaths: 'Deaths',
    uses: 'Uses',
    extraStat1: 'Extras',
    score: 'Score',
    timePlayed: 'Time Played',
    captures: 'Captures',
    defends: 'Defends',
    scorePerMinute: 'Score/min',
    downs: 'Downs',
    topTwentyFive: 'Top 25',
    topTen: 'Top 10',
    contracts: 'Contracts',
    revives: 'Revives',
    topFive: 'Top 5',
    gamesPlayed: 'Games Played',
    tokens: 'Tokens',
    cash: 'Cash',
    assists: 'Assists',
    setBacks: 'Setbacks',
    stabs: 'Stabs',
    denies: 'Denies',
    confirms: 'Confirms',
    objTime: 'Objective Time',
    wins: 'Wins',
    plants: 'Plants',
    defuses: 'Defuses',
    infected: 'Infected',
    time: 'Time',
  },
  modes: ["Gun Game", "Domination", "TDM", "Headquarters", "HardCore Domination", "Kill Confirmed Hardcore", "King Of The Hill", "Kill Confirmed", "Headquarters Hardcore", "Gunfight", "Plunder", "WARZONE", "Search And Destroy", "Grind", "Cyber Attack", "Team Deathmatch Hardcore", "br_all", "Search and Destroy Hardcore", "Ground War", "Cyber Attack HardCore", "Infected"],
};

module.exports = gunDataObj;